<?php  /*Elenco abbreviazioni*/

//La regex è 
//Partono da 1!!!!! altrimenti partirebbe da zero di default
$libram[1]="ge";
$libram[]="ex";
$libram[]="le";
$libram[]="nu";
$libram[]="de";
$libram[]="jos";
$libram[]="jg";
$libram[]="ru";
$libram[]="1sa";
$libram[]="2sa";
$libram[]="1ki";
$libram[]="2ki";
$libram[]="1ch";
$libram[]="2ch";
$libram[]="ezr";
$libram[]="ne";
$libram[]="es";
$libram[]="job";
$libram[]="ps";
$libram[]="pr";
$libram[]="ec";
$libram[]="ca";
$libram[]="isa";
$libram[]="jer";
$libram[]="la";
$libram[]="eze";
$libram[]="da";
$libram[]="ho";
$libram[]="joe";
$libram[]="am";
$libram[]="ob";
$libram[]="jon";
$libram[]="mic";
$libram[]="na";
$libram[]="hab";
$libram[]="zep";
$libram[]="hag";
$libram[]="zec";
$libram[]="mal";
$libram[]="mt";
$libram[]="mr";
$libram[]="lu";
$libram[]="joh";
$libram[]="ac";
$libram[]="ro";
$libram[]="1co";
$libram[]="2co";
$libram[]="ga";
$libram[]="eph";
$libram[]="php";
$libram[]="col";
$libram[]="1th";
$libram[]="2th";
$libram[]="1ti";
$libram[]="2ti";
$libram[]="tit";
$libram[]="phm";
$libram[]="heb";
$libram[]="jas";
$libram[]="1pe";
$libram[]="2pe";
$libram[]="1jo";
$libram[]="2jo";
$libram[]="3jo";
$libram[]="jude";
$libram[]="re";


//Italiano
$libr["italiano"][1]="Genesi";
$libr["italiano"][2]="Esodo";
$libr["italiano"][3]="Levitico";
$libr["italiano"][4]="Numeri";
$libr["italiano"][5]="Deuteronomio";
$libr["italiano"][6]="Giosuè";
$libr["italiano"][7]="Giudici";
$libr["italiano"][8]="Rut";
$libr["italiano"][9]="1 Samuele";
$libr["italiano"][10]="2 Samuele";
$libr["italiano"][11]="1 Re";
$libr["italiano"][]="2 Re";
$libr["italiano"][]="1 Cronache";
$libr["italiano"][]="2 Cronache";
$libr["italiano"][]="Esdra";
$libr["italiano"][]="Neemia";
$libr["italiano"][]="Ester";
$libr["italiano"][]="Giobbe";
$libr["italiano"][]="Salmi";
$libr["italiano"][]="Proverbi";
$libr["italiano"][]="Ecclesiaste";
$libr["italiano"][]="Il Cantico dei Cantici";
$libr["italiano"][]="Isaia";
$libr["italiano"][]="Geremia";
$libr["italiano"][]="Lamentazioni";
$libr["italiano"][]="Ezechiele";
$libr["italiano"][]="Daniele";
$libr["italiano"][]="Osea";
$libr["italiano"][]="Gioele";
$libr["italiano"][]="Amos";
$libr["italiano"][]="Abdia";
$libr["italiano"][]="Giona";
$libr["italiano"][]="Michea";
$libr["italiano"][]="Naum";
$libr["italiano"][]="Abacuc";
$libr["italiano"][]="Sofonia";
$libr["italiano"][]="Aggeo";
$libr["italiano"][]="Zaccaria";
$libr["italiano"][]="Malachia";
$libr["italiano"][]="Matteo";
$libr["italiano"][]="Marco";
$libr["italiano"][]="Luca";
$libr["italiano"][]="Giovanni";
$libr["italiano"][]="Atti";
$libr["italiano"][]="Romani";
$libr["italiano"][]="1 Corinti";
$libr["italiano"][]="2 Corinti";
$libr["italiano"][]="Galati";
$libr["italiano"][]="Efesini";
$libr["italiano"][]="Filippesi";
$libr["italiano"][]="Colossesi";
$libr["italiano"][]="1 Tessalonicesi";
$libr["italiano"][]="2 Tessalonicesi";
$libr["italiano"][]="1 Timoteo";
$libr["italiano"][]="2 Timoteo";
$libr["italiano"][]="Tito";
$libr["italiano"][]="Filemone";
$libr["italiano"][]="Ebrei";
$libr["italiano"][]="Giacomo";
$libr["italiano"][]="1 Pietro";
$libr["italiano"][]="2 Pietro";
$libr["italiano"][]="1 Giovanni";
$libr["italiano"][]="2 Giovanni";
$libr["italiano"][]="3 Giovanni";
$libr["italiano"][]="Giuda";
$libr["italiano"][]="Rivelazione";



//Italiano ridotto
$i=1;
$libr_rsx["italiano"][$i][]="Ge";
$i++;
$libr_rsx["italiano"][$i][]="Es";
$i++;
$libr_rsx["italiano"][$i][]="Le";
$i++;
$libr_rsx["italiano"][$i][]="Nu";
$i++;
$libr_rsx["italiano"][$i][]="Dt";
$i++;
$libr_rsx["italiano"][$i][]="Gios";
$libr_rsx["italiano"][$i][]="Gs";
$libr_rsx["italiano"][$i][]="Gio";
$i++;
$libr_rsx["italiano"][$i][]="Giu";
$libr_rsx["italiano"][$i][]="Gd";
$i++;
$libr_rsx["italiano"][$i][]="Ru";
$i++;
$libr_rsx["italiano"][$i][]="1Sa";
$i++;
$libr_rsx["italiano"][$i][]="2Sa";
$i++;
$libr_rsx["italiano"][$i][]="1Re";
$libr_rsx["italiano"][$i][]="1R";
$i++;
$libr_rsx["italiano"][$i][]="2Re";
$libr_rsx["italiano"][$i][]="2R";
$i++;
$libr_rsx["italiano"][$i][]="1Cr";
$i++;
$libr_rsx["italiano"][$i][]="2Cr";
$i++;
$libr_rsx["italiano"][$i][]="Esd";
$i++;
$libr_rsx["italiano"][$i][]="Ne";
$i++;
$libr_rsx["italiano"][$i][]="Est";
$i++;
$libr_rsx["italiano"][$i][]="Giob";
$libr_rsx["italiano"][$i][]="Gb";
$i++;
$libr_rsx["italiano"][$i][]="Sa";
$libr_rsx["italiano"][$i][]="Sl";
$i++;
$libr_rsx["italiano"][$i][]="Pv";
$i++;
$libr_rsx["italiano"][$i][]="Ec";
$i++;
$libr_rsx["italiano"][$i][]="Can";
$i++;
$libr_rsx["italiano"][$i][]="Isa";
$libr_rsx["italiano"][$i][]="Is";
$i++;
$libr_rsx["italiano"][$i][]="Ger";
$libr_rsx["italiano"][$i][]="Gr";
$i++;
$libr_rsx["italiano"][$i][]="La";
$libr_rsx["italiano"][$i][]="Lm";
$i++;
$libr_rsx["italiano"][$i][]="Ez";
$i++;
$libr_rsx["italiano"][$i][]="Da";
$i++;
$libr_rsx["italiano"][$i][]="Os";
$i++;
$libr_rsx["italiano"][$i][]="Gioe";
$libr_rsx["italiano"][$i][]="Gl";
$i++;
$libr_rsx["italiano"][$i][]="Am";
$i++;
$libr_rsx["italiano"][$i][]="Abd";
$i++;
$libr_rsx["italiano"][$i][]="Giona";
$libr_rsx["italiano"][$i][]="Gn";
$i++;
$libr_rsx["italiano"][$i][]="Mi";
$i++;
$libr_rsx["italiano"][$i][]="Na";
$i++;
$libr_rsx["italiano"][$i][]="Aba";
$i++;
$libr_rsx["italiano"][$i][]="So";
$libr_rsx["italiano"][$i][]="Sf";
$i++;
$libr_rsx["italiano"][$i][]="Ag";
$i++;
$libr_rsx["italiano"][$i][]="Za";
$i++;
$libr_rsx["italiano"][$i][]="Mal";
$i++;
$libr_rsx["italiano"][$i][]="Mt";
$i++;
$libr_rsx["italiano"][$i][]="Mr";
$i++;
$libr_rsx["italiano"][$i][]="Lu";
$i++;
$libr_rsx["italiano"][$i][]="Gv";
$i++;
$libr_rsx["italiano"][$i][]="At";
$i++;
$libr_rsx["italiano"][$i][]="Rm";
$i++;
$libr_rsx["italiano"][$i][]="1Co";
$i++;
$libr_rsx["italiano"][$i][]="2Co";
$i++;
$libr_rsx["italiano"][$i][]="Gal";
$i++;
$libr_rsx["italiano"][$i][]="Ef";
$i++;
$libr_rsx["italiano"][$i][]="Flp";
$i++;
$libr_rsx["italiano"][$i][]="Co";
$i++;
$libr_rsx["italiano"][$i][]="1Te";
$i++;
$libr_rsx["italiano"][$i][]="2Te";
$i++;
$libr_rsx["italiano"][$i][]="1Ti";
$i++;
$libr_rsx["italiano"][$i][]="2Ti";
$i++;
$libr_rsx["italiano"][$i][]="Tit";
$i++;
$libr_rsx["italiano"][$i][]="Flm";
$i++;
$libr_rsx["italiano"][$i][]="Eb";
$i++;
$libr_rsx["italiano"][$i][]="Gia";
$i++;
$libr_rsx["italiano"][$i][]="1Pi";
$i++;
$libr_rsx["italiano"][$i][]="2Pi";
$i++;
$libr_rsx["italiano"][$i][]="1Gv";
$i++;
$libr_rsx["italiano"][$i][]="2Gv";
$i++;
$libr_rsx["italiano"][$i][]="3Gv";
$i++;
$libr_rsx["italiano"][$i][]="Giuda";
$i++;
$libr_rsx["italiano"][$i][]="Riv";
$libr_rsx["italiano"][$i][]="Rv";




//Russo

$libr["pусский"][1]="Бытие";
$libr["pусский"][]="Исход";
$libr["pусский"][]="Левит";
$libr["pусский"][]="Числа";
$libr["pусский"][]="Второзаконие";
$libr["pусский"][]="Иисус Навин";
$libr["pусский"][]="Судей";
$libr["pусский"][]="Руфь";
$libr["pусский"][]="1 Самуила";
$libr["pусский"][]="2 Самуила";
$libr["pусский"][]="1 Царей";
$libr["pусский"][]="2 Царей";
$libr["pусский"][]="1 Летопись";
$libr["pусский"][]="2 Летопись";
$libr["pусский"][]="Ездра";
$libr["pусский"][]="Неемия";
$libr["pусский"][]="Эсфирь";
$libr["pусский"][]="Иов";
$libr["pусский"][]="Псалом";
$libr["pусский"][]="Притчи";
$libr["pусский"][]="Экклезиаст";
$libr["pусский"][]="Песнь песней";
$libr["pусский"][]="Исаия";
$libr["pусский"][]="Иеремия";
$libr["pусский"][]="Плач Иеремии";
$libr["pусский"][]="Иезекииль";
$libr["pусский"][]="Даниил";
$libr["pусский"][]="Осия";
$libr["pусский"][]="Иоиль";
$libr["pусский"][]="Амос";
$libr["pусский"][]="Авдий";
$libr["pусский"][]="Иона";
$libr["pусский"][]="Михей";
$libr["pусский"][]="Наум";
$libr["pусский"][]="Аввакум";
$libr["pусский"][]="Софония";
$libr["pусский"][]="Аггей";
$libr["pусский"][]="Захария";
$libr["pусский"][]="Малахия";
$libr["pусский"][]="Матфея";
$libr["pусский"][]="Марка";
$libr["pусский"][]="Луки";
$libr["pусский"][]="Иоанна";
$libr["pусский"][]="Деяния";
$libr["pусский"][]="Римлянам";
$libr["pусский"][]="1 Коринфянам";
$libr["pусский"][]="2 Коринфянам";
$libr["pусский"][]="Галатам";
$libr["pусский"][]="Эфесянам";
$libr["pусский"][]="Филиппийцам";
$libr["pусский"][]="Колоссянам";
$libr["pусский"][]="1 Фессалоникийцам";
$libr["pусский"][]="2 Фессалоникийцам";
$libr["pусский"][]="1 Тимофею";
$libr["pусский"][]="2 Тимофею";
$libr["pусский"][]="Титу";
$libr["pусский"][]="Филимону";
$libr["pусский"][]="Евреям";
$libr["pусский"][]="Иакова";
$libr["pусский"][]="1 Петра";
$libr["pусский"][]="2 Петра";
$libr["pусский"][]="1 Иоанна";
$libr["pусский"][]="2 Иоанна";
$libr["pусский"][]="3 Иоанна";
$libr["pусский"][]="Иуды";
$libr["pусский"][]="Откровение";

//Giapponese

$libr["日本語"][1]="創世記";
$libr["日本語"][]="出エジプト記";
$libr["日本語"][]="レビ記";
$libr["日本語"][]="民数記";
$libr["日本語"][]="申命記";
$libr["日本語"][]="ヨシュア";
$libr["日本語"][]="裁き人";
$libr["日本語"][]="ルツ";
$libr["日本語"][]="サムエル第一";
$libr["日本語"][]="サムエル第二";
$libr["日本語"][]="列王第一";
$libr["日本語"][]="列王第二";
$libr["日本語"][]="歴代第一";
$libr["日本語"][]="歴代第二";
$libr["日本語"][]="エズラ";
$libr["日本語"][]="ネヘミヤ";
$libr["日本語"][]="エステル";
$libr["日本語"][]="ヨブ";
$libr["日本語"][]="詩編";
$libr["日本語"][]="箴言";
$libr["日本語"][]="伝道の書";
$libr["日本語"][]="ソロモンの歌";
$libr["日本語"][]="イザヤ";
$libr["日本語"][]="エレミヤ";
$libr["日本語"][]="哀歌";
$libr["日本語"][]="エゼキエル";
$libr["日本語"][]="ダニエル";
$libr["日本語"][]="ホセア";
$libr["日本語"][]="ヨエル";
$libr["日本語"][]="アモス";
$libr["日本語"][]="オバデヤ";
$libr["日本語"][]="ヨナ";
$libr["日本語"][]="ミカ";
$libr["日本語"][]="ナホム";
$libr["日本語"][]="ハバクク";
$libr["日本語"][]="ゼパニヤ";
$libr["日本語"][]="ハガイ";
$libr["日本語"][]="ゼカリヤ";
$libr["日本語"][]="マラキ";
$libr["日本語"][]="マタイ";
$libr["日本語"][]="マルコ";
$libr["日本語"][]="ルカ";
$libr["日本語"][]="ヨハネ";
$libr["日本語"][]="使徒";
$libr["日本語"][]="ローマ";
$libr["日本語"][]="コリント第一";
$libr["日本語"][]="コリント第二";
$libr["日本語"][]="ガラテア";
$libr["日本語"][]="エフェソス";
$libr["日本語"][]="フィリピ";
$libr["日本語"][]="コロサイ";
$libr["日本語"][]="テサロニケ第一";
$libr["日本語"][]="テサロニケ第二";
$libr["日本語"][]="テモテ第一";
$libr["日本語"][]="テモテ第二";
$libr["日本語"][]="テトス";
$libr["日本語"][]="フィレモン";
$libr["日本語"][]="ヘブライ";
$libr["日本語"][]="ヤコブ";
$libr["日本語"][]="ペテロ第一";
$libr["日本語"][]="ペテロ第二";
$libr["日本語"][]="ヨハネ第一";
$libr["日本語"][]="ヨハネ第二";
$libr["日本語"][]="ヨハネ第三";
$libr["日本語"][]="ユダ";
$libr["日本語"][]="啓示";


// inglese

$libr["English"][1]="Genesis";
$libr["English"][]="Exodus";
$libr["English"][]="Leviticus";
$libr["English"][]="Numbers";
$libr["English"][]="Deuteronomy";
$libr["English"][]="Joshua";
$libr["English"][]="Judges";
$libr["English"][]="Ruth";
$libr["English"][]="1 Samuel";
$libr["english"][]="2 Samuel";
$libr["english"][]="1 Kings";
$libr["english"][]="2 Kings";
$libr["english"][]="1 Chronicles";
$libr["english"][]="2 Chronicles";
$libr["english"][]="Ezra";
$libr["english"][]="Nehemiah";
$libr["english"][]="Esther";
$libr["english"][]="Job";
$libr["english"][]="Psalms";
$libr["english"][]="Proverbs";
$libr["english"][]="Ecclesiastes";
$libr["english"][]="Song of Solomon";
$libr["english"][]="Isaiah";
$libr["english"][]="Jeremiah";
$libr["english"][]="Lamentations";
$libr["english"][]="Ezekiel";
$libr["english"][]="Daniel";
$libr["english"][]="Hosea";
$libr["english"][]="Joel";
$libr["english"][]="Amos";
$libr["english"][]="Obadiah";
$libr["english"][]="Jonah";
$libr["english"][]="Micah";
$libr["english"][]="Nahum";
$libr["english"][]="Habakkuk";
$libr["english"][]="Zephaniah";
$libr["english"][]="Haggai";
$libr["english"][]="Zechariah";
$libr["english"][]="Malachi";
$libr["english"][]="Matthew";
$libr["english"][]="Mark";
$libr["english"][]="Luke";
$libr["english"][]="John";
$libr["english"][]="Acts";
$libr["english"][]="Romans";
$libr["english"][]="1 Corinthians";
$libr["english"][]="2 Corinthians";
$libr["english"][]="Galatians";
$libr["english"][]="Ephesians";
$libr["english"][]="Philippians";
$libr["english"][]="Colossians";
$libr["english"][]="1 Thessalonians";
$libr["english"][]="2 Thessalonians";
$libr["english"][]="1 Timothy";
$libr["english"][]="2 Timothy";
$libr["english"][]="Titus";
$libr["english"][]="Philemon";
$libr["english"][]="Hebrews";
$libr["english"][]="James";
$libr["english"][]="1 Peter";
$libr["english"][]="2 Peter";
$libr["english"][]="1 John";
$libr["english"][]="2 John";
$libr["english"][]="3 John";
$libr["english"][]="Jude";
$libr["english"][]="Revelation";


//Spagnolo

$libr["español"][1]="Génesis";
$libr["español"][]="Éxodo";
$libr["español"][]="Levítico";
$libr["español"][]="Números";
$libr["español"][]="Deuteronomio";
$libr["español"][]="Josué";
$libr["español"][]="Jueces";
$libr["español"][]="Rut";
$libr["español"][]="1 Samuel";
$libr["español"][]="2 Samuel";
$libr["español"][]="1 Reyes";
$libr["español"][]="2 Reyes";
$libr["español"][]="1 Crónicas";
$libr["español"][]="2 Crónicas";
$libr["español"][]="Esdras";
$libr["español"][]="Nehemías";
$libr["español"][]="Ester";
$libr["español"][]="Job";
$libr["español"][]="Salmos";
$libr["español"][]="Proverbios";
$libr["español"][]="Eclesiastés";
$libr["español"][]="El Cantar de los Cantares";
$libr["español"][]="Isaías";
$libr["español"][]="Jeremías";
$libr["español"][]="Lamentaciones";
$libr["español"][]="Ezequiel";
$libr["español"][]="Daniel";
$libr["español"][]="Oseas";
$libr["español"][]="Joel";
$libr["español"][]="Amós";
$libr["español"][]="Abdías";
$libr["español"][]="Jonás";
$libr["español"][]="Miqueas";
$libr["español"][]="Nahúm";
$libr["español"][]="Habacuc";
$libr["español"][]="Sofonías";
$libr["español"][]="Ageo";
$libr["español"][]="Zacarías";
$libr["español"][]="Malaquías";
$libr["español"][]="Mateo";
$libr["español"][]="Marcos";
$libr["español"][]="Lucas";
$libr["español"][]="Juan";
$libr["español"][]="Hechos";
$libr["español"][]="Romanos";
$libr["español"][]="1 Corintios";
$libr["español"][]="2 Corintios";
$libr["español"][]="Gálatas";
$libr["español"][]="Efesios";
$libr["español"][]="Filipenses";
$libr["español"][]="Colosenses";
$libr["español"][]="1 Tesalonicenses";
$libr["español"][]="2 Tesalonicenses";
$libr["español"][]="1 Timoteo";
$libr["español"][]="2 Timoteo";
$libr["español"][]="Tito";
$libr["español"][]="Filemón";
$libr["español"][]="Hebreos";
$libr["español"][]="Santiago";
$libr["español"][]="1 Pedro";
$libr["español"][]="2 Pedro";
$libr["español"][]="1 Juan";
$libr["español"][]="2 Juan";
$libr["español"][]="3 Juan";
$libr["español"][]="Judas";
$libr["español"][]="Revelación";


/*Classi di gestione interna */
$lib_class['Pentateuco'][0]=1; //Genesi
$lib_class['Pentateuco'][1]=5; // Deuteronomio
$lib_class['Pentateuco'][2]='Pentateuco'; // Deuteronomio //$t_lang['$lang']['Pentateuco']
$lib_class['Pentateuco'][3]='#FFC341'; // Deuteronomio

$lib_class['Storici'][0]=6; //Giosuè
$lib_class['Storici'][1]=18;  //Giobbe
$lib_class['Storici'][2]='Storici';  //Giobbe
$lib_class['Storici'][3]="#5BB6E4";

$lib_class['Poetici'][0]=19; //Salmi
$lib_class['Poetici'][1]=22; //Cantico
$lib_class['Poetici'][2]='Poetici'; //Cantico
$lib_class['Poetici'][3]="#FF5555";

$lib_class['Profetici'][0]=23; //Isaia
$lib_class['Profetici'][1]=39; //Malachia
$lib_class['Profetici'][2]='Profetici'; //Malachia
$lib_class['Profetici'][3]="#FFDCA8";

$lib_class['Vangeli'][0]=40; //Matteo
$lib_class['Vangeli'][1]=44; //Giovanni
$lib_class['Vangeli'][2]='Vangeli'; //Giovanni
$lib_class['Vangeli'][3]="#17C400";


$lib_class['Lettere'][0]=45; //Atti
$lib_class['Lettere'][1]=66; //Rivelazione
$lib_class['Lettere'][2]='Lettere'; //Rivelazione
$lib_class['Lettere'][3]="#896FFF";


