<?php

//
// $Id: test.php 2055 2009-11-06 23:09:58Z shodan $
//
require("util/top_foot_inc.php");
top3();
// require ( "funzioni.php" );
require_once ("util/mysqlutil.php");
connetti();


?>
<li><strong>sticky, with arrows</strong>:This sticky clueTip has its "close"
 text in the title bar. It won't close until you close it, or until you hover
  over another clue-tipped link. It also displays an arrow on one of its sides, 
pointing to the invoking element. 




<a
	rel="l2.php?l=1"
	href="l2.php"
	id="sticky"
	title=""
	style=""
	class="jtip"
>sticky clueTip with arrows</a></li>
 	<a
	rel="l2.php?l=0"
	href="l2.php?l=0"
	id="sticky"
	title=""
	style=""
	class="jtip"
>0</a>  	<a
	rel="l2.php?l=1"
	href="l2.php?l=1"
	id="sticky"
	title=""
	style=""
	class="jtip"
>1</a>  	<a
	rel="l2.php?l=2"
	href="l2.php?l=2"
	id="sticky"
	title=""
	style=""
	class="jtip"
>2</a>  	<a
	rel="l2.php?l=3"
	href="l2.php?l=3"
	id="sticky"
	title=""
	style=""
	class="jtip"
>3</a>  	<a
	rel="l2.php?l=4"
	href="l2.php?l=4"
	id="sticky"
	title=""
	style=""
	class="jtip"
>4</a>  	<a
	rel="l2.php?l=5"
	href="l2.php?l=5"
	id="sticky"
	title=""
	style=""
	class="jtip"
>5</a>  	<a
	rel="l2.php?l=6"
	href="l2.php?l=6"
	id="sticky"
	title=""
	style=""
	class="jtip"
>6</a>  	<a
	rel="l2.php?l=7"
	href="l2.php?l=7"
	id="sticky"
	title=""
	style=""
	class="jtip"
>7</a>  	<a
	rel="l2.php?l=8"
	href="l2.php?l=8"
	id="sticky"
	title=""
	style=""
	class="jtip"
>8</a>  	<a
	rel="l2.php?l=9"
	href="l2.php?l=9"
	id="sticky"
	title=""
	style=""
	class="jtip"
>9</a>  	<a
	rel="l2.php?l=10"
	href="l2.php?l=10"
	id="sticky"
	title=""
	style=""
	class="jtip"
>10</a>  	<a
	rel="l2.php?l=11"
	href="l2.php?l=11"
	id="sticky"
	title=""
	style=""
	class="jtip"
>11</a>  	<a
	rel="l2.php?l=12"
	href="l2.php?l=12"
	id="sticky"
	title=""
	style=""
	class="jtip"
>12</a>  	<a
	rel="l2.php?l=13"
	href="l2.php?l=13"
	id="sticky"
	title=""
	style=""
	class="jtip"
>13</a>  	<a
	rel="l2.php?l=14"
	href="l2.php?l=14"
	id="sticky"
	title=""
	style=""
	class="jtip"
>14</a>  	<a
	rel="l2.php?l=15"
	href="l2.php?l=15"
	id="sticky"
	title=""
	style=""
	class="jtip"
>15</a>  	<a
	rel="l2.php?l=16"
	href="l2.php?l=16"
	id="sticky"
	title=""
	style=""
	class="jtip"
>16</a>  	<a
	rel="l2.php?l=17"
	href="l2.php?l=17"
	id="sticky"
	title=""
	style=""
	class="jtip"
>17</a>  	<a
	rel="l2.php?l=18"
	href="l2.php?l=18"
	id="sticky"
	title=""
	style=""
	class="jtip"
>18</a>  	<a
	rel="l2.php?l=19"
	href="l2.php?l=19"
	id="sticky"
	title=""
	style=""
	class="jtip"
>19</a>  	<a
	rel="l2.php?l=20"
	href="l2.php?l=20"
	id="sticky"
	title=""
	style=""
	class="jtip"
>20</a>  	<a
	rel="l2.php?l=21"
	href="l2.php?l=21"
	id="sticky"
	title=""
	style=""
	class="jtip"
>21</a>  	<a
	rel="l2.php?l=22"
	href="l2.php?l=22"
	id="sticky"
	title=""
	style=""
	class="jtip"
>22</a>  	<a
	rel="l2.php?l=23"
	href="l2.php?l=23"
	id="sticky"
	title=""
	style=""
	class="jtip"
>23</a>  	<a
	rel="l2.php?l=24"
	href="l2.php?l=24"
	id="sticky"
	title=""
	style=""
	class="jtip"
>24</a>  	<a
	rel="l2.php?l=25"
	href="l2.php?l=25"
	id="sticky"
	title=""
	style=""
	class="jtip"
>25</a>  	<a
	rel="l2.php?l=26"
	href="l2.php?l=26"
	id="sticky"
	title=""
	style=""
	class="jtip"
>26</a>  	<a
	rel="l2.php?l=27"
	href="l2.php?l=27"
	id="sticky"
	title=""
	style=""
	class="jtip"
>27</a>  	<a
	rel="l2.php?l=28"
	href="l2.php?l=28"
	id="sticky"
	title=""
	style=""
	class="jtip"
>28</a>  	<a
	rel="l2.php?l=29"
	href="l2.php?l=29"
	id="sticky"
	title=""
	style=""
	class="jtip"
>29</a>  	<a
	rel="l2.php?l=30"
	href="l2.php?l=30"
	id="sticky"
	title=""
	style=""
	class="jtip"
>30</a>  	<a
	rel="l2.php?l=31"
	href="l2.php?l=31"
	id="sticky"
	title=""
	style=""
	class="jtip"
>31</a>  	<a
	rel="l2.php?l=32"
	href="l2.php?l=32"
	id="sticky"
	title=""
	style=""
	class="jtip"
>32</a>  	<a
	rel="l2.php?l=33"
	href="l2.php?l=33"
	id="sticky"
	title=""
	style=""
	class="jtip"
>33</a>  	<a
	rel="l2.php?l=34"
	href="l2.php?l=34"
	id="sticky"
	title=""
	style=""
	class="jtip"
>34</a>  	<a
	rel="l2.php?l=35"
	href="l2.php?l=35"
	id="sticky"
	title=""
	style=""
	class="jtip"
>35</a>  	<a
	rel="l2.php?l=36"
	href="l2.php?l=36"
	id="sticky"
	title=""
	style=""
	class="jtip"
>36</a>  	<a
	rel="l2.php?l=37"
	href="l2.php?l=37"
	id="sticky"
	title=""
	style=""
	class="jtip"
>37</a>  	<a
	rel="l2.php?l=38"
	href="l2.php?l=38"
	id="sticky"
	title=""
	style=""
	class="jtip"
>38</a>  	<a
	rel="l2.php?l=39"
	href="l2.php?l=39"
	id="sticky"
	title=""
	style=""
	class="jtip"
>39</a>  	<a
	rel="l2.php?l=40"
	href="l2.php?l=40"
	id="sticky"
	title=""
	style=""
	class="jtip"
>40</a>  	<a
	rel="l2.php?l=41"
	href="l2.php?l=41"
	id="sticky"
	title=""
	style=""
	class="jtip"
>41</a>  	<a
	rel="l2.php?l=42"
	href="l2.php?l=42"
	id="sticky"
	title=""
	style=""
	class="jtip"
>42</a>  	<a
	rel="l2.php?l=43"
	href="l2.php?l=43"
	id="sticky"
	title=""
	style=""
	class="jtip"
>43</a>  	<a
	rel="l2.php?l=44"
	href="l2.php?l=44"
	id="sticky"
	title=""
	style=""
	class="jtip"
>44</a>  	<a
	rel="l2.php?l=45"
	href="l2.php?l=45"
	id="sticky"
	title=""
	style=""
	class="jtip"
>45</a>  	<a
	rel="l2.php?l=46"
	href="l2.php?l=46"
	id="sticky"
	title=""
	style=""
	class="jtip"
>46</a>  	<a
	rel="l2.php?l=47"
	href="l2.php?l=47"
	id="sticky"
	title=""
	style=""
	class="jtip"
>47</a>  	<a
	rel="l2.php?l=48"
	href="l2.php?l=48"
	id="sticky"
	title=""
	style=""
	class="jtip"
>48</a>  	<a
	rel="l2.php?l=49"
	href="l2.php?l=49"
	id="sticky"
	title=""
	style=""
	class="jtip"
>49</a>  del libro 50